# exclude vendored packages, images, maya files, generated ui files
exclude: "vendor|\/.*png|\/.*svg|\/.*ma|gen\/.*py$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
        language_version: python3
      - id: check-yaml
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
